spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
  sql:
    init:
      encoding: utf-8
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 468350384619-mo3c9i344nkk1uleulq790l6sj4lgnhh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: ksy@gmail.com
  secret_key: study-springboot